### ISSUE TITLE
Running Error of the beamsearch.py 

### ISSUE THREAD

**Issue by JackAILab** [CMACH508/AlphaDrug#1]
# Running Code BUG of beamsearch.py
Dear authors, I get an error **` TypeError: full() received an invalid combination of arguments - got (tuple, float, device=int), but expected one of:`**,   when I run your beamsearch.py file to perform the "running beam search on protein 1a9u". 

In your source code of beamsearch.py (line 76), **`tgt_mask = nn.Transformer.generate_square_subsequent_mask(model, smiMaxLen).tolist()`**, two parameters are put in the  **`nn.Transformer.generate_square_subsequent_mask`** function. 

However, I find that this function only needs one parameter, just **"smiMaxLen"** is enough, should I delete the parameter **" model"**, will it influence the running result?

I am looking forward to your early reply, thank you a lot!

**Comment by JackAILab** [comment]
I received some errors after I delete that parameter (model) as follows:
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/112920087/198954536-031adeff-c890-43a4-90ed-e09b9361fdf7.png">

**Comment by BL-Lac149597870** [comment]
1. The first error (beamsearch.py (line 76)) is caused by version conflicts of pytorch.  I met this error before too. Deleting the parameter " model" **will not** influence the running result.
2. As for the affinity error, try to install **smina** before running beam search. It seems you did not install all required packages?
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/31134008/199011735-554be861-1a01-4d71-a178-4535386478e1.png">

**Comment by JackAILab** [comment]
Thank you for your detailed reply, I have solved this! 



---- Replied Message ----
| From | ***@***.***> |
| Date | 10/31/2022 20:50 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [CMACH508/AlphaDrug] Running Error of the beamsearch.py (Issue #1) |

The first error (beamsearch.py (line 76)) is caused by version conflicts of pytorch. I met this error before too. Deleting the parameter " model" will not influence the running result.
As for the affinity error, try to install smina before running beam search. It seems you did not install all required packages?
